package com.itsgaurav.csseasy.constants;


public class ListItems {

    public static final String[] CSSListItems = {

            "CSS Introduction",
            "CSS Syntax",
            "CSS How To",
            "CSS Colors ",
            "CSS Background",
            "CSS Borders",
            "CSS Margins",
            "CSS Padding",
            "CSS Height/Width",
            "CSS Text",
            "CSS Fonts",
            "CSS Links",
            "CSS Lists",
            "CSS Tables",
            "CSS Box Model",
            "CSS Outline",
            "CSS Display",
            "CSS Max-Width",
            "CSS Position",
            "CSS Float",
            "CSS Inline-block",
            "CSS Align",
            "CSS Combinator",
            "CSS Pseudo-class",
            "CSS Pseudo-elements",
            "CSS Navigation Bar",
            "CSS Dropdown",
            "CSS Tooltips",
            "CSS Image Gallery",
            "CSS Image Opacity",
            "CSS Image Sprites",
            "CSS Attr Selectors",
            "CSS Forms",
            "CSS Counters",

            "CSS3 Introduction",
            "CSS3 Rounded Corners",
            "CSS3 Border Images",
            "CSS3 Backgrounds",
            "CSS3 Colors",
            "CSS3 Gradients",
            "CSS3 Shadows",
            "CSS3 Text",
            "CSS3 Fonts",
            "CSS3 2D Transforms",
            "CSS3 3D Transforms",
            "CSS3 Transitions",
            "CSS3 Animations",
            "CSS3 Images",
            "CSS3 Buttons",
            "CSS3 Pagination",
            "CSS3 Multiple Columns",
            "CSS3 User Interface",
            "CSS3 Box Sizing",
            "CSS3 Flexbox",
            "CSS3 Filters",
            "CSS3 Media Queries",
            "CSS3 MQ Examples",

            "CSS RWD Introduction",
            "RWD Viewport",
            "RWD Grid View",
            "RWD Media Queries",
            "RWD Images",
            "RWD Video",
            "RWD Framework"
    };
    public static final String[] listItemHeaderValue = {
            ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS,
            ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS,
            ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS,
            ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS,
            ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS,
            ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS,
            ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS,
            ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS,
            ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS,
            ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS,
            ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS, ConstantValue.CATEGORY_BASICS,
            ConstantValue.CATEGORY_BASICS,

            ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3,
            ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3,
            ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3,
            ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3,
            ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3,
            ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3,
            ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3,
            ConstantValue.CATEGORY_CSS3, ConstantValue.CATEGORY_CSS3,

            ConstantValue.CATEGORY_RESPONSIVE, ConstantValue.CATEGORY_RESPONSIVE,
            ConstantValue.CATEGORY_RESPONSIVE, ConstantValue.CATEGORY_RESPONSIVE,
            ConstantValue.CATEGORY_RESPONSIVE, ConstantValue.CATEGORY_RESPONSIVE,
            ConstantValue.CATEGORY_RESPONSIVE
    };
}
